import { useEffect, useMemo, useState } from 'react';
import { Bell, Check, ChevronDown, CircleAlert, RefreshCw, SlidersHorizontal, Sparkles, TrendingUp } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { fetchMe } from '../api/client';
import DashboardLayout from '../components/DashboardLayout.jsx';
import StatCard from '../components/StatCard.jsx';
import EmailCard from '../components/EmailCard.jsx';
import EmailDetail from '../components/EmailDetail.jsx';
import PriorityBadge from '../components/PriorityBadge.jsx';
import LoadingSkeleton from '../components/LoadingSkeleton.jsx';
import EmptyState from '../components/EmptyState.jsx';
import ErrorState from '../components/ErrorState.jsx';
import Toast from '../components/Toast.jsx';
import { mockEmails } from '../data/mockEmails.js';

function useAuth() {
  const navigate = useNavigate();
  useEffect(() => {
    // TEMPORARY DEVELOPMENT-ONLY DASHBOARD BYPASS
    if (import.meta.env.DEV) return;
    fetchMe().catch(() => {
      localStorage.removeItem('pp_token');
      navigate('/login');
    });
  }, [navigate]);
}
function Page({ title, children }) { useAuth(); return <DashboardLayout title={title}>{children}</DashboardLayout>; }

export default function Dashboard() { return <Page title="Dashboard"><div className="pp-welcome"><div><p className="overline">Friday, 07 August 2026</p><h2>Good morning, Naomi <em>👋</em></h2><p>Here’s the signal from your inbox today.</p></div><button className="button button--primary" onClick={() => window.location.href = '/dashboard/inbox'}>Open priority inbox <span>→</span></button></div><div className="pp-stat-grid"><StatCard label="Total emails" value="1,284" note="+8.4% this week" /><StatCard label="High priority" value="24" note="6 need attention" accent="pp-stat-card--coral" /><StatCard label="Unread" value="87" note="12 since yesterday" /><StatCard label="AI processed" value="1,197" note="93.2% of inbox" accent="pp-stat-card--lime" /></div><div className="pp-dashboard-grid"><section className="pp-panel pp-priority-panel"><div className="pp-panel-heading"><div><p className="overline">Your next move</p><h3>Priority inbox</h3></div><a href="/dashboard/inbox">View all <span>↗</span></a></div>{mockEmails.slice(0, 4).map((email) => <EmailCard key={email.id} email={email} onSelect={() => { window.location.href = `/dashboard/inbox?email=${email.id}`; }} />)}</section><section className="pp-panel pp-signal-panel"><div className="pp-panel-heading"><div><p className="overline">AI signal</p><h3>Inbox at a glance</h3></div><Sparkles size={17} /></div><div className="pp-signal-score"><strong>92<span>%</span></strong><p>of your inbox is<br />calmly classified</p></div><div className="pp-bars"><div><span>High priority</span><i><b style={{ width: '18%' }} /></i><em>24</em></div><div><span>Medium priority</span><i><b className="medium" style={{ width: '39%' }} /></i><em>51</em></div><div><span>Low priority</span><i><b className="low" style={{ width: '66%' }} /></i><em>87</em></div></div><div className="pp-signal-note"><TrendingUp size={16} /><span>Response time is <b>18% faster</b> this week.</span></div></section></div></Page>; }

export function Inbox({ importantOnly = false, initialFilter = 'ALL' }) {
  const [selected, setSelected] = useState(null);
  const [filter, setFilter] = useState(importantOnly ? 'HIGH' : initialFilter);
  const [status, setStatus] = useState('ALL');
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [aiLoading, setAiLoading] = useState(false);
  const [loadError, setLoadError] = useState(false);
  const [toast, setToast] = useState('');
  useEffect(() => { const timer = setTimeout(() => setLoading(false), 420); return () => clearTimeout(timer); }, []);
  const loadEmails = () => { setLoadError(false); setLoading(true); setTimeout(() => setLoading(false), 420); };
  const list = useMemo(() => mockEmails.filter((e) => {
    const haystack = `${e.sender} ${e.subject} ${e.preview} ${e.body}`.toLowerCase();
    return (filter === 'ALL' || e.priority === filter) && (status === 'ALL' || (status === 'UNREAD' ? e.unread : !e.unread)) && (!importantOnly || e.important) && haystack.includes(query.toLowerCase());
  }), [filter, importantOnly, query, status]);
  const selectEmail = (email) => { setSelected(email); setAiLoading(true); setToast(`Email classified as ${email.priority}`); setTimeout(() => setAiLoading(false), 650); };
  const clearFilters = () => { setFilter(importantOnly ? 'HIGH' : 'ALL'); setStatus('ALL'); setQuery(''); };
  const previewEmail = selected || list[0];
  return <Page title={importantOnly ? 'High priority' : 'Priority inbox'}><div className="pp-page-intro"><div><p className="overline">{importantOnly ? 'Only what matters most' : 'All your email, understood'}</p><h2>{importantOnly ? 'High priority' : 'Priority inbox'} <span className="pp-count">{list.length}</span></h2><p>Every message arrives with a reason to act — or not.</p></div><div className="pp-inbox-tools"><label className="pp-inline-search"><SlidersHorizontal size={15} /><input aria-label="Search emails" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search emails..." /></label><button className="pp-filter-button" onClick={loadEmails}><RefreshCw size={14} /> Sync inbox</button></div></div><div className="pp-filter-toolbar"><div className="pp-filter-tabs" aria-label="Priority filters">{['ALL', 'HIGH', 'MEDIUM', 'LOW'].map((item) => <button className={filter === item ? 'active' : ''} key={item} onClick={() => setFilter(item)}>{item === 'ALL' ? 'All' : <PriorityBadge priority={item} />}</button>)}</div><div className="pp-status-tabs" aria-label="Read status filters">{['ALL', 'UNREAD', 'READ'].map((item) => <button className={status === item ? 'active' : ''} key={item} onClick={() => setStatus(item)}>{item === 'ALL' ? 'All status' : item[0] + item.slice(1).toLowerCase()}</button>)}</div>{(query || filter !== (importantOnly ? 'HIGH' : 'ALL') || status !== 'ALL') && <button className="pp-clear-filters" onClick={clearFilters}>Clear filters</button>}</div>{loading ? <div className="pp-workspace"><LoadingSkeleton /></div> : loadError ? <div className="pp-workspace"><ErrorState title="Unable to load emails" message="We couldn't load your emails right now." onRetry={loadEmails} /></div> : <div className="pp-workspace"><section className="pp-email-list">{list.map((email) => <EmailCard key={email.id} email={email} selected={selected?.id === email.id || (!selected && email.id === list[0]?.id)} onSelect={selectEmail} />)}{!list.length && <EmptyState title={query || status !== 'ALL' ? 'No emails found' : importantOnly ? 'No high-priority emails' : 'No emails yet'} message={query || status !== 'ALL' ? 'Try changing your search or filters.' : importantOnly ? "You're all caught up." : 'Your inbox is empty. New emails will appear here automatically.'} action={(query || status !== 'ALL') ? { label: 'Clear filters', onClick: clearFilters } : undefined} />}</section>{previewEmail && <section className={`pp-workspace-detail${selected ? ' is-open' : ''}`}><EmailDetail email={previewEmail} aiLoading={aiLoading} onBack={() => setSelected(null)} /></section>}</div>}<Toast message={toast} onClose={() => setToast('')} /></Page>;
}

export function Analytics() { return <Page title="Analytics"><div className="pp-page-intro"><div><p className="overline">The bigger picture</p><h2>Your inbox, in context.</h2><p>See how PriorityPulse is helping your attention move with intention.</p></div><button className="pp-filter-button"><ChevronDown size={15} /> Last 7 days</button></div><div className="pp-analytics-grid"><section className="pp-panel pp-chart-panel"><div className="pp-panel-heading"><div><p className="overline">Volume</p><h3>Weekly email flow</h3></div><span className="pp-chart-legend"><i /> All email</span></div><div className="pp-chart"><div className="pp-y-labels"><span>240</span><span>180</span><span>120</span><span>60</span><span>0</span></div><div className="pp-chart-area"><div className="pp-grid-lines"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 600 190" preserveAspectRatio="none"><path d="M0 142 C50 120,70 132,110 108 S170 116,205 90 S270 105,300 74 S360 93,400 51 S465 65,500 35 S560 52,600 18" fill="none" stroke="#ddff5b" strokeWidth="4" /><path d="M0 142 C50 120,70 132,110 108 S170 116,205 90 S270 105,300 74 S360 93,400 51 S465 65,500 35 S560 52,600 18 V190 H0Z" fill="rgba(221,255,91,.14)" /></svg><div className="pp-x-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></div></section><section className="pp-panel pp-distribution"><div className="pp-panel-heading"><div><p className="overline">Classification</p><h3>Priority distribution</h3></div><Sparkles size={16} /></div><div className="pp-donut"><div><strong>162</strong><span>messages</span></div></div><div className="pp-legend"><span><i className="high" />High <b>24</b></span><span><i className="medium" />Medium <b>51</b></span><span><i className="low" />Low <b>87</b></span></div></section></div><div className="pp-stat-grid pp-analytics-stats"><StatCard label="Avg. confidence" value="91.8%" note="+2.1% this week" /><StatCard label="Processed" value="1,197" note="93.2% of inbox" accent="pp-stat-card--lime" /><StatCard label="Saved triage time" value="2h 18m" note="Across your team" /></div></Page>; }

export function Notifications() { const [toast, setToast] = useState(''); const [items, setItems] = useState([{ icon: CircleAlert, title: 'High-priority email detected', copy: 'Apex Financial needs your response', time: '8 minutes ago', tone: 'coral' }, { icon: Sparkles, title: 'Email classified', copy: 'Q3 contract renewal → HIGH', time: '8 minutes ago', tone: 'lime' }, { icon: Bell, title: 'Daily inbox summary', copy: '24 emails processed', time: 'Yesterday at 6:00 PM', tone: 'blue' }]); const clear = () => { setItems([]); setToast('Changes saved'); }; return <Page title="Notifications"><div className="pp-page-intro"><div><p className="overline">Stay in the loop</p><h2>Signals worth seeing.</h2><p>Quiet by default. Clear when it matters.</p></div>{items.length > 0 && <button className="pp-filter-button" onClick={clear}><Check size={15} /> Mark all read</button>}</div><section className="pp-notification-list">{items.length ? items.map(({ icon: Icon, title, copy, time, tone }) => <article key={title} className="pp-notification"><span className={`pp-notification-icon ${tone}`}><Icon size={18} /></span><div><strong>{title}</strong><p>{copy}</p><small>{time}</small></div><i /></article>) : <EmptyState title="No new notifications" message="You're all caught up." />}</section><Toast message={toast} onClose={() => setToast('')} /></Page>; }

export function Settings() { return <Page title="Settings"><div className="pp-page-intro"><div><p className="overline">Your workspace</p><h2>Make it yours.</h2><p>Control how PriorityPulse fits into the way you work.</p></div></div><div className="pp-settings-grid"><SettingsSection title="Account" eyebrow="01"><SettingRow label="Email" value="naomi@prioritypulse.ai" /><SettingRow label="Profile" value="Naomi Adams" action="Edit" /></SettingsSection><SettingsSection title="Gmail" eyebrow="02"><SettingRow label="Connection status" value="Connected" status /><SettingRow label="Sync frequency" value="Every 5 minutes" action="Change" /></SettingsSection><SettingsSection title="Notifications" eyebrow="03"><SettingRow label="High-priority alerts" value="On" toggle /><SettingRow label="Browser notifications" value="On" toggle /></SettingsSection><SettingsSection title="AI classification" eyebrow="04"><SettingRow label="Classification settings" value="Balanced" action="Adjust" /><SettingRow label="Confidence threshold" value="80%" action="Change" /></SettingsSection></div></Page>; }
function SettingsSection({ title, eyebrow, children }) { return <section className="pp-panel pp-settings-section"><p className="overline">{eyebrow}</p><h3>{title}</h3><div>{children}</div></section>; }
function SettingRow({ label, value, action, status, toggle }) { return <div className="pp-setting-row"><span>{label}</span><div>{status && <i className="pp-status-dot" />}<b>{value}</b>{toggle ? <span className="pp-toggle is-on"><i /></span> : action && <button>{action} →</button>}</div></div>; }
